# Generated by Django 2.0.5 on 2018-05-12 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180512_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pref_foot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 12, 12, 37, 48, 227804)),
        ),
    ]
