# Generated by Django 2.0.5 on 2018-05-12 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20180512_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Player'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team_name',
            field=models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='posts.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='guest_team',
            field=models.ForeignKey(db_column='guest_team', on_delete=django.db.models.deletion.CASCADE, related_name='guest_team', to='posts.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(db_column='home_team', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='posts.Team'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deciding_president',
            field=models.ForeignKey(db_column='deciding_president', on_delete=django.db.models.deletion.CASCADE, to='posts.President'),
        ),
        migrations.AlterField(
            model_name='participatesin',
            name='match_id',
            field=models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Match'),
        ),
        migrations.AlterField(
            model_name='participatesin',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='belong_to_team_name',
            field=models.ForeignKey(db_column='belong_to_team_name', on_delete=django.db.models.deletion.CASCADE, to='posts.Team'),
        ),
        migrations.AlterField(
            model_name='playsin',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Player'),
        ),
        migrations.AlterField(
            model_name='playsin',
            name='team_name',
            field=models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='posts.Team'),
        ),
        migrations.AlterField(
            model_name='position',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Player'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 12, 12, 53, 1, 468253)),
        ),
        migrations.AlterField(
            model_name='president',
            name='team_name',
            field=models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='posts.Team'),
        ),
        migrations.AlterField(
            model_name='proposeoffer',
            name='offer_id',
            field=models.ForeignKey(db_column='offer_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Offer'),
        ),
        migrations.AlterField(
            model_name='proposeoffer',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Player'),
        ),
        migrations.AlterField(
            model_name='proposeoffer',
            name='president_id',
            field=models.ForeignKey(db_column='president_id', on_delete=django.db.models.deletion.CASCADE, to='posts.President'),
        ),
        migrations.AlterField(
            model_name='proposetrade',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Player'),
        ),
        migrations.AlterField(
            model_name='proposetrade',
            name='president_id',
            field=models.ForeignKey(db_column='president_id', on_delete=django.db.models.deletion.CASCADE, to='posts.President'),
        ),
        migrations.AlterField(
            model_name='proposetrade',
            name='trade_id',
            field=models.ForeignKey(db_column='trade_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Trade'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='match_id',
            field=models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Match'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='player_id',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='posts.Player'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='team_name',
            field=models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='posts.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium_name',
            field=models.ForeignKey(db_column='stadium_name', on_delete=django.db.models.deletion.CASCADE, to='posts.Stadium'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='deciding_president',
            field=models.ForeignKey(db_column='deciding_president', on_delete=django.db.models.deletion.CASCADE, to='posts.President'),
        ),
    ]
