# Generated by Django 2.0.5 on 2018-05-13 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20180512_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='player_name',
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 13, 19, 54, 3, 592276)),
        ),
    ]
