# Generated by Django 2.0.5 on 2018-05-13 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20180513_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='agent',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 13, 20, 52, 15, 902937)),
        ),
    ]
